"""Add table log_orders and add import init

Revision ID: 1851ac2609b4
Revises: 4635de9dcb2d
Create Date: 2022-07-05 18:35:29.776481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1851ac2609b4'
down_revision = '4635de9dcb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_barang', sa.String(length=50), nullable=True),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('jumlah_terjual', sa.Integer(), nullable=True),
    sa.Column('jenis_barang', sa.String(length=50), nullable=True),
    sa.Column('tanggal_transaksi', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_orders_id'), 'log_orders', ['id'], unique=False)
    op.create_index(op.f('ix_log_orders_tanggal_transaksi'), 'log_orders', ['tanggal_transaksi'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_orders_tanggal_transaksi'), table_name='log_orders')
    op.drop_index(op.f('ix_log_orders_id'), table_name='log_orders')
    op.drop_table('log_orders')
    # ### end Alembic commands ###
