"""Add FK jenis_barang_id to table transaksi

Revision ID: 5b791d057719
Revises: 2c86621473af
Create Date: 2022-07-09 14:29:47.578814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b791d057719'
down_revision = '2c86621473af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_orders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_log_orders_id', table_name='log_orders')
    op.create_foreign_key(None, 'log_orders', 'transaksi', ['id'], ['id'])
    op.drop_constraint('transaksi_jenis_barang_id_fkey', 'transaksi', type_='foreignkey')
    op.create_foreign_key(None, 'transaksi', 'jenis_barang', ['jenis_barang_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaksi', type_='foreignkey')
    op.create_foreign_key('transaksi_jenis_barang_id_fkey', 'transaksi', 'barang', ['jenis_barang_id'], ['id'])
    op.drop_constraint(None, 'log_orders', type_='foreignkey')
    op.create_index('ix_log_orders_id', 'log_orders', ['id'], unique=False)
    op.alter_column('log_orders', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
