"""Add tables barang, jenis_barang, stocks, and transaksi

Revision ID: 10aaabd43dfc
Revises: 1851ac2609b4
Create Date: 2022-07-09 10:31:45.067934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aaabd43dfc'
down_revision = '1851ac2609b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_barang',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jenis_barang', sa.String(length=36), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jenis_barang_id'), 'jenis_barang', ['id'], unique=False)
    op.create_table('log_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_barang', sa.String(length=50), nullable=True),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('jumlah_terjual', sa.Integer(), nullable=True),
    sa.Column('jenis_barang', sa.String(length=50), nullable=True),
    sa.Column('tanggal_transaksi', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_orders_id'), 'log_orders', ['id'], unique=False)
    op.create_index(op.f('ix_log_orders_tanggal_transaksi'), 'log_orders', ['tanggal_transaksi'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('barang',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jenis_barang_id', sa.BigInteger(), nullable=True),
    sa.Column('nama_barang', sa.String(length=36), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jenis_barang_id'], ['jenis_barang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barang_id'), 'barang', ['id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('barang_id', sa.BigInteger(), nullable=True),
    sa.Column('nama_barang', sa.String(length=36), nullable=True),
    sa.Column('stock', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_table('transaksi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stocks_id', sa.BigInteger(), nullable=True),
    sa.Column('barang_id', sa.BigInteger(), nullable=True),
    sa.Column('jenis_barang_id', sa.BigInteger(), nullable=True),
    sa.Column('nama_barang', sa.String(length=36), nullable=True),
    sa.Column('stock', sa.BigInteger(), nullable=True),
    sa.Column('jumlah_terjual', sa.BigInteger(), nullable=True),
    sa.Column('jenis_barang', sa.BigInteger(), nullable=True),
    sa.Column('tanggal_transaksi', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.ForeignKeyConstraint(['jenis_barang_id'], ['barang.id'], ),
    sa.ForeignKeyConstraint(['stocks_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_id'), 'transaksi', ['id'], unique=False)
    op.create_index(op.f('ix_transaksi_tanggal_transaksi'), 'transaksi', ['tanggal_transaksi'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaksi_tanggal_transaksi'), table_name='transaksi')
    op.drop_index(op.f('ix_transaksi_id'), table_name='transaksi')
    op.drop_table('transaksi')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_barang_id'), table_name='barang')
    op.drop_table('barang')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_log_orders_tanggal_transaksi'), table_name='log_orders')
    op.drop_index(op.f('ix_log_orders_id'), table_name='log_orders')
    op.drop_table('log_orders')
    op.drop_index(op.f('ix_jenis_barang_id'), table_name='jenis_barang')
    op.drop_table('jenis_barang')
    # ### end Alembic commands ###
