"""Add revision of column of transaksi table

Revision ID: 2c86621473af
Revises: 10aaabd43dfc
Create Date: 2022-07-09 10:40:44.436002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c86621473af'
down_revision = '10aaabd43dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaksi', 'jenis_barang',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaksi', 'jenis_barang',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
