"""Add table log_orders

Revision ID: 4635de9dcb2d
Revises: 6bb21d4ff249
Create Date: 2022-07-05 18:20:30.558388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4635de9dcb2d'
down_revision = '6bb21d4ff249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
